### ISSUE TITLE
A few quick suggested improvements

### ISSUE THREAD

**Issue by geerlingguy** [Greg-Boggs/ansible-hosting#1]
I noticed a few things that can help streamline things a bit:

  1. You can use the [geerlingguy.security](https://github.com/geerlingguy/ansible-role-security) role to configure the 'first 5 minutes' security things, as well as auto-updates.
  2. You could provide a Galaxy `requirements.yml` file (see https://github.com/geerlingguy/drupal-vm/tree/master/provisioning#adding-and-updating-galaxy-roles for example) so users can just run one `ansible-galaxy install -r requirements.yml` instead of running a bunch of independent role install commands :)

**Comment by Greg-Boggs** [comment]
Improvements added. It still need a bit of work adding a sudo user, but thanks for the direction!
